name: STRiker
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.9
  - numpy=2.0.2
  - scipy=1.13.1
  - pysam=0.23.3
  - openpyxl=3.1.5
  - pip
  - pip:
      - biopython==1.81
      - matplotlib==3.9.4
      - pandas==2.3.0
      - seaborn==0.13.2
